import json, os

def chaveOrd(emd):
    return emd["dataEMD"]
    
f = open("emd.json")

bd = json.load(f)
f.close()
bd.sort(reverse=True, key=chaveOrd)

preHTML = """
<!DOCTYPE html>
<html>
    <head>
        <title>Lista de Exames Médicos Desportivos</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="w3.css">
        <meta charset="utf-8"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-pale-red">
              <h3>Lista de Exames Médicos Desportivos</h3>
            </header>
            
            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
"""

posHTLM = """
                </ul>
            </div>
            
            <footer class="w3-container w3-pale-red">
                <h5>Generated by EMDApp::EngWeb2024::a95454</h5>
            </footer>            
        </div>
    </body>
</html> 
"""

conteudo = ""

for e in bd:
    conteudo += f"""
                    <li>
                        <a href="emd{e['index']}.html"> 
                            {e['dataEMD']}: {e['nome']['primeiro']} {e['nome']['último']}
                        </a>
                    </li>
"""
    
pagHTML = preHTML + conteudo + posHTLM

f = open('./emdSite/index.html', 'w')
f.write(pagHTML)
f.close()

# print(os.getcwd()) # mostra qual a diretoria que estou a trabalhar
